### PR TITLE
feat: add signed & unsigned integer colour repr

### PR DESCRIPTION
**Pull request by backwardspy**
todo:

- [x] naming
- [x] tests
- [x] docs

### CODE REVIEW

**Comment by uncenter** [comment]
Naming seems good to me btw :)

**Comment by NeonGamerBot-QK** [comment]
any updates on this?

**Comment by backwardspy** [comment]
> any updates on this?

i forgot about it amongst a bunch of recent irl stuff. thanks for bring it back to my attention! i'll see if i can get it sorted today.

**Comment by uncenter** [comment]
Feels weird adding this onto the color object itself (original palette data doesn't include this, can be generated via information on the color object already), I would think a filter would be better. 🤔

**Comment by backwardspy** [comment]
the whiskers models are not directly related to the palette json, so i'm not averse to adding new fields for whiskers.

that said, i did try a filter for this initially but i didn't find a design i liked that wasn't also cumbersome to use. i also considered just having a single int field that was tied to the hex format for component order/inclusion, but that felt too unintuitive.

i settled on the idea of having these three fields that i feel to be the most common formats for now, then in future we could also add a filter for cases where you need more customisation and don't mind the extra overhead of having to use a filter for it. something like `{{red | intrep(bits=32, order="rgba")}}` for example.

let me know if you have any other ideas!

**Comment by uncenter** [comment]
Well I was thinking having a filter for each type of repr, so `{{ red | sint32 }}` instead of `{{ red.sint32 }}`, and so on. I thought this was the design of the API when first testing it out in Aliucord but I had to take a look at this PR's code to understand. This feels similar to the `css_rgb`-type functions, where you can format the existing RGB data into the CSS format. In this case, you can format the same existing RGB data into this different format.

**Comment by backwardspy** [comment]
i see it more like the hex format - an exact identical/lossless representation of those RGB channels.

**Comment by uncenter** [comment]
Sure, whatever you are good with. Anything else left for this PR?

**Comment by backwardspy** [comment]
think so yeah, i'll update those when i get back and get this moving :+1: thanks for the input!

**Pull request merged**
